config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  #root 'welcome#index'
  resources :articles
  root 'articles#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
	belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
	has_many :articles
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_attached_file :avtar, styles:{medium: "300x300", thumb:"100x100"}
  validates_attachment_content_type :avtar, content_type: /\Aimage\/.*\Z/
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	before_action :configure_permitted_parameters, if: :devise_controller?

	protected
		def configure_permitted_parameters
			devise_parameter_sanitizer.permit(:sign_up){|u| u.permit(:username, :email, :password, :password_confirmation, :remember_me, :avtar, :avtar_cache)}
			devise_parameter_sanitizer.permit(:account_update){|u| u.permit(:username,:password,:password_confirmation,:current_password,:avtar)}
		end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
	def index
		@articles=Article.all
	end

	def new
		if user_signed_in?
      		@article = current_user.articles.build
    	else
      		redirect_to articles_path, alert:"Login First"
    end
	end

	def edit
		@article=Article.find(params[:id])
	end

	def create
		@article=current_user.articles.build(article_params)
		if @article.save
			redirect_to @article
		else
			render 'new'
	end
	end

	def update
		@article= Article.find(params[:id])
		if @article.update(article_params)
			redirect_to @article_params
		else
			render 'edit'
		end
	end

	def show
		@article=Article.find(params[:id])
	end

	def destroy
		@article= Article.find(params[:id])
		@article.destroy

		redirect_to articles_path
	end

	def article_params
		params.require(:article).permit(:title,:text)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/articles/edit.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
	<p>
		<%= form.label :title %><br>
		<%= form.text_field :title%>
	</p>

	<p>
		<%= form.label :text %><br>
		<%= form.text_area :text%>
	</p>

	<p>
		<%= form.submit %>		
	</p>
	<%end%>

	<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<h1> Listing Articles </h1>
<%= link_to 'New article', new_article_path %>
<table>
<tr>
	<th>Title</th>
	<th>Text</th>
	<th></th>
</tr>

<% @articles.each do |article| %>
<tr>
	<td><%=article.title%></td>
	<td><%=article.text%></td>
	<td><%= link_to 'Show', article_path(article)%></td>
	<%# <td><%= link_to 'Edit', edit_article_path(article)%></td>
	<%# <td><%= link_to 'Delete', article_path(article), method: :delete, data:{confirm: 'Are you sure?'}%></td>
</tr>
<%end%>
</table>

app/views/articles/new.html.erb
<%= form_with scope: :article, url: articles_path, local: true do |form| %>
	<p>
		<%= form.label :title %><br>
		<%= form.text_field :title%>
	</p>

	<p>
		<%= form.label :text %><br>
		<%= form.text_area :text%>
	</p>

	<p>
		<%= form.submit %>		
	</p>
	<%end%>

	<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p>
	<strong> Title: </strong>
	<%= @article.title %>
</p>

<p>
	<strong> Text: </strong>
	<%= @article.text %>
</p>

<% if user_signed_in?%>
	<% if @article.user_id==current_user.id %>
		<%= link_to 'Edit', edit_article_path(@article) %>
		<%= link_to 'Destroy', @article, method: :delete, data: { confirm: 'Are you sure?' } %>
	<%end%>
<%end%>
<%# <%= link_to 'Edit', edit_article_path(@article) %>
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if user_signed_in? %>
        Logged in as <strong><%=current_user.email%> <strong>
        <%= link_to "Edit Profile", edit_user_registration_path%>
      <%#  <%= link_to "Show Profile", user_path(current_user)%>
        <%= link_to "Log out", destroy_user_session_path, method: :delete%>
      <%else%>
        <%= link_to "Signup", new_user_registration_path%> or
        <%= link_to "Login", new_user_session_path%>
      <%end%>  
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>

    <%= yield %>
    </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome#index</h1>
<p>Find me in app/views/welcome/index.html.erb</p>